// Top-level build file for ACCA-NG.
plugins {
    id 'com.android.application' version '8.7.3' apply false
    id 'org.jetbrains.kotlin.android' version '2.0.21' apply false
    id 'org.jetbrains.kotlin.plugin.parcelize' version '2.0.21' apply false
    id 'com.google.devtools.ksp' version '2.0.21-1.0.25' apply false
}

ext {
    versions = [
            libsuVersion  : '3.0.2',
            roomVersion   : '2.6.1',
            lifecycle     : '2.8.6',
            coroutines    : '1.9.0',
            viewpager     : "1.0.0",
            material      : "1.12.0",
            browser       : "1.8.0",
            appcompat     : "1.7.0",
            coreKtx       : "1.15.0",
            constraint    : "2.1.4",
            fragmentKtx   : "1.8.2",
            gson          : "2.11.0",
            moshi         : "1.15.0"
    ]
}
