package mattecarra.accapp.acc

import com.google.gson.Gson
import com.google.gson.JsonObject
import mattecarra.accapp.acc.v202107280.AccHandler
import mattecarra.accapp.models.AccConfig
import mattecarra.accapp.models.ProfileActivation
import org.junit.Assert.*
import org.junit.Test
import java.io.IOException

/** Outputs generated by ACC-NG's production shell against synthetic files. */
class FrontendContractTest {
    private fun resource(name: String) = requireNotNull(javaClass.getResource("/acc-ng/$name")).readText()
    private val fixtures = Gson().fromJson(resource("frontend-contract.json"), JsonObject::class.java)
    private val contract = requireNotNull(NgEngineContract.parse(fixtures["module"].asString))
    private val handler = AccHandler(202610095, contract)
    private fun output(group: String, name: String) = fixtures.getAsJsonObject(group).getAsJsonObject(name)["output"].asString
    private fun code(group: String, name: String) = fixtures.getAsJsonObject(group).getAsJsonObject(name)["code"].asInt

    @Test fun defaultOutputPreservesTheModernConfigContract() {
        val config = handler.parseConfig(output("config", "default"))
        assertEquals(AccConfig.ConfigCapacity(5, 70, 75), config.configCapacity)
        assertEquals(AccConfig.ConfigTemperature(35, 50, 90, 45), config.configTemperature)
        assertNull(config.configCurrMax)
        assertNull(config.configVoltage.max)
        assertNull(config.configCoolDown)
        assertNull(config.configChargeSwitch)
        assertTrue(config.configIsAutomaticSwitchingEnabled)
        assertTrue(config.prioritizeBatteryIdleMode)
    }

    @Test fun profileReadbackPreservesLimitsHooksAndManualSwitch() {
        val config = handler.parseConfig(output("config", "profile"))
        assertEquals(AccConfig.ConfigCapacity(2, 50, 60), config.configCapacity)
        assertEquals(4100, config.configVoltage.max)
        assertEquals(500, config.configCurrMax)
        assertEquals("battery/current_max::500::1800", config.configOnBoot)
        assertEquals("battery/voltage_max::4100::4200", config.configOnPlug)
        assertEquals("battery/charging_enabled 1 0", config.configChargeSwitch)
        assertFalse(config.configIsAutomaticSwitchingEnabled)
        assertTrue(config.configTemperature.resumeTemperatureOverridesCapacity)
        assertTrue(handler.getUpdateAccTemperatureCommand(config.configTemperature).endsWith("resume_temp=40r"))
        assertTrue(ProfileActivation.matches(config, Gson().fromJson(Gson().toJson(config), AccConfig::class.java)))
    }

    @Test fun voltageCapacityRemainsMillivolts() {
        val config = handler.parseConfig(output("config", "voltage-profile"))
        assertEquals(AccConfig.ConfigCapacity(2, 3800, 3900), config.configCapacity)
    }

    @Test fun legacyStoredProfileMatchesItsMigratedReadback() {
        val saved = Gson().fromJson(resource("legacy-profile.json"), AccConfig::class.java)
        assertNull(saved.configTemperature.resumeTemperature)
        assertEquals(90, saved.configTemperature.pause)
        val readback = handler.parseConfig(output("config", "profile").replace("resume_temp=40r", "resume_temp=45"))
        assertTrue(ProfileActivation.matches(readback, saved))
        assertFalse(ProfileActivation.matches(readback.copy(configCapacity = readback.configCapacity.copy(pause = 61)), saved))
        assertTrue(handler.getUpdateAccTemperatureCommand(saved.configTemperature).endsWith("resume_temp=45"))
    }

    @Test fun milliAndMicroSensorsProduceIdenticalAppMeasurements() {
        for (name in listOf("micro-charging", "milli-charging", "verbose")) {
            val info = handler.parseBatteryInfo(output("info", name))
            assertEquals(name, 1800000f, info.currentNow, 1f)
            assertEquals(name, 4200000f, info.voltageNow, 1f)
            assertEquals(name, 7560000f, info.powerNow, 1f)
            assertEquals(60, info.capacity)
            assertEquals(32, info.temperature)
            assertTrue(info.hasCurrentReading)
            assertTrue(info.isCharging())
        }
    }

    @Test fun flagsAndQnovoReadTheirOwnFields() {
        val info = handler.parseBatteryInfo(output("info", "micro-charging"))
        assertTrue(info.isInputSuspend)
        assertFalse(info.isInputCurrentLimited)
        assertTrue(info.isStepChargingEnabled)
        assertFalse(info.isSwJeitaEnabled)
        assertFalse(info.isTaperControlEnabled)
        assertTrue(info.isChargeDisabled)
        assertFalse(info.isChargeDone)
        assertTrue(info.isParallelDisabled)
        assertEquals(12345, info.currentQnovo)
        assertEquals("Li-ion", info.technology)
        assertEquals(42, info.cycleCount)
    }

    @Test fun negativeCurrentZeroAndUnknownAreDifferent() {
        val discharge = handler.parseBatteryInfo(output("info", "discharging"))
        assertEquals(-750000f, discharge.currentNow, 1f)
        assertEquals("Discharging", discharge.status)
        val zero = handler.parseBatteryInfo(output("info", "zero"))
        assertEquals(0f, zero.currentNow, 0f)
        assertTrue(zero.hasCurrentReading)
        for (name in listOf("missing-current", "malformed-current")) {
            assertFalse(handler.parseBatteryInfo(output("info", name)).hasCurrentReading)
        }
        assertEquals("Not charging", handler.parseBatteryInfo(output("info", "idle")).status)
    }

    @Test fun malformedNumericPrefixesAreNotReadings() {
        val info = handler.parseBatteryInfo("CURRENT_NOW=12broken\nVOLTAGE_NOW=NaN\nSTATUS=Chargingbroken\nCHARGE_DISABLE=12")
        assertFalse(info.hasCurrentReading)
        assertEquals(0f, info.voltageNow, 0f)
        assertEquals("Unknown", info.status)
        assertFalse(info.isChargeDisabled)
    }

    @Test fun batteryNamesHealthAndNegativeTemperatureArePreserved() {
        val info = handler.parseBatteryInfo("NAME=main-battery\nHEALTH=Over voltage\nTEMP=-25\nCHARGE_TYPE=USB_PD")
        assertEquals("main-battery", info.name)
        assertEquals("Over voltage", info.health)
        assertEquals("USB_PD", info.chargeType)
        assertEquals(-2, info.temperature)
    }

    @Test fun missingVoltageIsNotInvented() {
        for (name in listOf("missing-voltage", "malformed-voltage")) {
            assertEquals(0f, handler.parseBatteryInfo(output("info", name)).voltageNow, 0f)
        }
    }

    @Test fun daemonStatesAndFailuresAreDistinct() {
        assertTrue(AccOutput.daemonRunning(code("daemon", "running")))
        assertTrue(AccOutput.daemonRunning(8))
        assertFalse(AccOutput.daemonRunning(code("daemon", "stopped")))
        for (code in listOf(1, 7, 127, 124)) {
            try { AccOutput.daemonRunning(code); fail("Failure $code is not stopped") }
            catch (_: IOException) { }
        }
    }

    @Test fun idleProbeRequiresSuccessfulCompleteOutput() {
        assertEquals(15 to true, AccOutput.idleSupported(code("switch", "idle"), output("switch", "idle")))
        assertEquals(0 to false, AccOutput.idleSupported(code("switch", "working"), output("switch", "working")))
        assertEquals(10 to false, AccOutput.idleSupported(code("switch", "failed"), output("switch", "failed")))
        for (code in listOf(7, 16, 124)) assertEquals(code to false, AccOutput.idleSupported(code, "- battIdleMode=true"))
        assertEquals(15 to false, AccOutput.idleSupported(15, "incomplete output"))
    }

    @Test fun releaseVersionParserIgnoresNoiseAndRejectsPartialNumbers() {
        assertEquals(202610095, AccOutput.version(output("version", "current")))
        assertEquals(202310160, AccOutput.version("warning\nv2023.10.16 (202310160)\n"))
        assertNull(AccOutput.version("v1.0.5-ng (202610095oops)"))
        assertNull(AccOutput.version("command not found"))
    }

    @Test fun switchListPreservesManualSuffixAndFailsClosedOnCommandErrors() {
        val switches = AccOutput.switches(code("switch", "list"), output("switch", "list"))
        assertEquals(listOf("battery/charging_enabled 1 0", "battery/batt_slate_mode 0 1 --"), switches)
        assertTrue(AccOutput.switches(127, output("switch", "list")).isEmpty())
    }

    @Test fun cooldownAndResetFlagsSurviveConfigReadback() {
        val config = handler.parseConfig(output("config", "cooldown"))
        assertEquals(AccConfig.ConfigCoolDown(55, 30, 5), config.configCoolDown)
        assertTrue(config.configResetUnplugged)
        assertTrue(config.configResetBsOnPause)
    }
}
