// Run with Node.js and sharp available on NODE_PATH.
// The geometry in mark-path.json was generated by Google Stitch.
const fs = require('node:fs/promises');
const path = require('node:path');
const sharp = require('sharp');

const root = path.resolve(__dirname, '../..');
const res = path.join(root, 'app/src/main/res');

async function main() {
  const mark = JSON.parse(await fs.readFile(path.join(__dirname, 'mark-path.json'), 'utf8'));
  const { path: d, yellow, charcoal } = mark;
  const glyph = color => `<g transform="translate(26.5 29.25) scale(.55)"><path fill="${color}" fill-rule="evenodd" d="${d}"/></g>`;
  const svg = (body, viewBox = '18 18 72 72') => `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="${viewBox}">${body}</svg>\n`;
  const tile = (round = false, circle = false) => svg(
    circle
      ? `<circle cx="54" cy="54" r="36" fill="${yellow}"/>${glyph(charcoal)}`
      : `<rect x="18" y="18" width="72" height="72" rx="${round ? 16 : 0}" fill="${yellow}"/>${glyph(charcoal)}`,
  );
  const write = (file, data) => fs.writeFile(path.join(__dirname, file), data);
  await write('mark.svg', svg(`<path fill="${yellow}" fill-rule="evenodd" d="${d}"/>`, '0 0 100 100'));
  await write('icon.svg', tile());
  await write('icon-rounded.svg', tile(true));
  await write('icon-round.svg', tile(false, true));

  const vector = color => `<?xml version="1.0" encoding="utf-8"?>
<!-- ACCA-NG energy monogram, designed with Google Stitch.
     Geometry shared with design/branding/mark-path.json.
     Fits within the adaptive icon's central 66dp safe circle. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <group android:translateX="26.5" android:translateY="29.25"
        android:scaleX="0.55" android:scaleY="0.55">
        <path android:fillColor="${color}" android:fillType="evenOdd"
            android:pathData="${d}" />
    </group>
</vector>
`;
  await fs.writeFile(path.join(res, 'drawable/ic_launcher_foreground.xml'), vector(charcoal));
  await fs.writeFile(path.join(res, 'drawable/ic_launcher_monochrome.xml'), vector('#FFFFFF'));
  await fs.writeFile(path.join(res, 'values/ic_launcher_background.xml'), `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">${yellow}</color>
</resources>
`);

  for (const [density, size] of Object.entries({mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192})) {
    for (const [name, source] of [['ic_launcher', tile(true)], ['ic_launcher_round', tile(false, true)]]) {
      await sharp(Buffer.from(source)).resize(size, size).png().toFile(path.join(res, `mipmap-${density}`, `${name}.png`));
    }
  }
  await sharp(Buffer.from(tile())).png().toFile(path.join(__dirname, 'icon.png'));
  await sharp(Buffer.from(tile(true))).png().toFile(path.join(__dirname, 'icon-rounded.png'));
  await sharp(Buffer.from(tile())).png().toFile(path.join(root, 'fastlane/metadata/android/en-US/images/icon.png'));
  for (const file of ['logo', 'logo-dark']) {
    await sharp(path.join(__dirname, `${file}.svg`)).resize({width: 1600}).png().toFile(path.join(__dirname, `${file}.png`));
  }

  const darkLogo = (await fs.readFile(path.join(__dirname, 'logo-dark.svg'), 'utf8'))
    .replace(/width="\d+" height="160"/, 'x="66" y="170" width="795" height="200"');
  const lightLogo = (await fs.readFile(path.join(__dirname, 'logo.svg'), 'utf8'))
    .replace(/width="\d+" height="160"/, 'x="64" y="459" width="630" height="150"');
  const iconAt = (x, y, size, circle = false) => tile(!circle, circle)
    .replace('width="512" height="512"', `x="${x}" y="${y}" width="${size}" height="${size}"`);
  const preview = `<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="920" viewBox="0 0 1440 920">
    <rect width="1440" height="920" fill="#101216"/>
    <g font-family="sans-serif">
      <text x="64" y="67" fill="${yellow}" font-size="18" letter-spacing="3">ACCA-NG / NOVA IDENTIDADE</text>
      <text x="64" y="110" fill="#94989E" font-size="19">Criada com Google Stitch · Energia em amarelo elétrico</text>
      <rect x="40" y="145" width="842" height="268" rx="24" fill="${charcoal}"/>
      ${darkLogo}
      <rect x="40" y="433" width="842" height="216" rx="24" fill="#F7F6F0"/>
      ${lightLogo}
      <text x="70" y="622" fill="#676A6F" font-size="16">A de ACCA + corte angular de energia</text>
      <rect x="906" y="145" width="494" height="504" rx="24" fill="${charcoal}"/>
      <text x="942" y="195" fill="#F7F6F0" font-size="19">Ícone Android</text>
      ${iconAt(975, 236, 176)}${iconAt(1180, 263, 122, true)}
      <text x="997" y="450" fill="#A2A5AA" font-size="16">Adaptativo</text>
      <text x="1209" y="450" fill="#A2A5AA" font-size="16">Circular</text>
      ${iconAt(965, 503, 48)}${iconAt(1043, 515, 24)}
      <text x="961" y="585" fill="#A2A5AA" font-size="16">48 px</text>
      <text x="1036" y="585" fill="#A2A5AA" font-size="16">24 px</text>
      <rect x="1140" y="492" width="95" height="68" rx="15" fill="#DEE4CF"/>
      <svg x="1154" y="499" width="67" height="54" viewBox="18 18 72 72">${glyph('#384326')}</svg>
      <text x="1145" y="585" fill="#A2A5AA" font-size="16">Temático</text>
      <rect x="40" y="675" width="420" height="122" rx="20" fill="${yellow}"/>
      <text x="70" y="719" fill="${charcoal}" font-size="18">Amarelo elétrico</text>
      <text x="70" y="760" fill="${charcoal}" font-size="25">#FFD600</text>
      <rect x="480" y="675" width="420" height="122" rx="20" fill="${charcoal}" stroke="#35383D"/>
      <text x="510" y="719" fill="#F7F6F0" font-size="18">Grafite</text>
      <text x="510" y="760" fill="#F7F6F0" font-size="25">#171A1F</text>
      <rect x="920" y="675" width="480" height="122" rx="20" fill="#F7F6F0"/>
      <text x="950" y="719" fill="${charcoal}" font-size="18">Branco quente</text>
      <text x="950" y="760" fill="${charcoal}" font-size="25">#F7F6F0</text>
      <text x="64" y="861" fill="#94989E" font-size="18">Vetores SVG · Logo com letras em curvas · Ícones Android e versão monocromática</text>
    </g>
  </svg>`;
  await write('preview.svg', preview);
  await sharp(Buffer.from(preview)).png().toFile(path.join(__dirname, 'preview.png'));
}

main().catch(error => { console.error(error); process.exitCode = 1; });
