package mattecarra.accapp.acc

// Generated by ACC-NG tools/export_contract.py; edit the engine source.
internal object GeneratedExternalPower {
    const val source = "# Incoming power: 0 connected, 1 disconnected, 2 unknown.\n# Shared with events and the frontend. An unreadable/invalid source cannot\n# prove unplug; a valid connected source wins over incomplete other sources.\nng_power_state() {\n  local file= value= type= name= seen=false unknown=false\n  for file in \"\${1:-.}\"/*/online; do\n    [ -e \"\$file\" ] || [ -L \"\$file\" ] || continue\n    name=\${file%/online}; name=\${name##*/}\n    name=\$(printf '%s' \"\$name\" | tr '[:upper:]' '[:lower:]')\n    case \"\$name\" in battery|bms|otg) continue;; esac\n    type=\$(cat \"\${file%/online}/type\" 2>/dev/null) || type=\n    type=\$(printf '%s' \"\$type\" | tr '[:upper:]' '[:lower:]')\n    case \"\$type\" in battery|bms|otg|usb_otg|usb_dfp) continue;; esac\n    value=\$(cat \"\$file\" 2>/dev/null) || { unknown=true; continue; }\n    case \"\$value\" in 1) return 0;; 0) seen=true;; *) unknown=true;; esac\n  done\n  \$seen && ! \$unknown && return 1\n  return 2\n}\n"
}
